repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
<<<<<<< HEAD
    rev: v2.3.0
=======
    rev: v4.1.0
>>>>>>> 7f471f1d4d16edaffefac55e129427f587dab1c2
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
